### ISSUE TITLE
Free Game step 1

### ISSUE THREAD

**Issue by zahraaliaghazadeh** [zahraaliaghazadeh/battleship#6]
- [ ] Styling of squares , water(Blue), hit a square of a ship(Light Green), clicking on a square again (Red), clicking when not your turn(maybe notification pop up), one ship destroyed (Dark Green)

**Comment by Dhunt5** [comment]
colors are changed per our discussion.  Added X for hit, O for miss as symbols.  Logic for tracking ships hit added.
